### ISSUE TITLE
provider/azure: support `userData` on top of `customData`

### ISSUE THREAD

**Issue by tormath1** [coreos/ignition#1347]
# Feature Request #

Azure supports now[^1] `userData` through IMDS. TL; DR: it looks like IMDSv1 for AWS.

## Environment ##

Azure provider.

## Desired Feature ##

To keep backward compatibility, we could first try to fetch `userData` then fallback on `customData` in case of failure. According to the doc[^2], we can fetch the `userData` through:
```
curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/userData?api-version=2021-01-01&format=text" | base64 --decode
```

## Other Information ##

* This issue is created for tracking purposes
* A PR is being tested on Flatcar's fork: https://github.com/flatcar-linux/ignition/pull/39
* Cross reference: https://github.com/flatcar-linux/Flatcar/issues/656

[^1]: https://docs.microsoft.com/en-us/azure/virtual-machines/user-data
[^2]: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/instance-metadata-service?tabs=linux#get-user-data

**Comment by bgilbert** [comment]
Thanks for pointing this out!

If users are going to expect to put configs in userdata, we should certainly be able to read them from there.  I agree it's reasonable to fetch userdata and fall back to custom data if userdata is missing.

---

For completeness, I'll note that there are some unfortunate things about how userdata is [positioned](https://docs.microsoft.com/en-us/azure/virtual-machines/user-data#what-is-user-data):

> User data can be retrieved from Azure Instance Metadata Service(IMDS) after provision.
> User data is persistent. It will be available during the lifetime of the VM.

These are bad, actually.  We haven't formally taken a position on whether it's reasonable to store secrets in userdata, but users often do it.  If it's possible to access that userdata from an untrusted container, users will have to take additional measures to prevent it, e.g. by firewalling off the metadata service.

> User data can be updated from outside the VM, without stopping or rebooting the VM.

This doesn't really affect Ignition, since it only runs once, but could confuse users when their changes to userdata are ignored.
