### ISSUE TITLE
Fetch should have a dependency on network-online.target instead of network.target

### ISSUE THREAD

**Issue by lnykryn** [coreos/ignition#1594]
In logs I saw quite a lot of messages like:

Mar 29 15:09:40 localhost.localdomain ignition[830]: GET error: Get "********": dial tcp ******* connect: network is unreachable

And that is caused by this:
https://github.com/coreos/ignition/blob/main/dracut/30ignition/ignition-fetch.service#L22

After=network.target only makes sense during the shutdown. 
You should use
After=network-online.target
Wants=network-online.target

network.target only means that we started the tool responsible for networking, not the network itself.

You can find details here https://systemd.io/NETWORK_ONLINE/

**Comment by cgwalters** [comment]
The best thing to do really is monitor the kernel routing tables and avoid trying to send packets when it won't work at all.  This is what's enabled by e.g. [GNetworkMonitor](https://libsoup.org/gio/GNetworkMonitor.html).  Not sure anyone's done a Go equivalent.  Maybe someone should make a `/usr/bin/wait-for-connectable <hostname|IP>`

**Comment by bgilbert** [comment]
In addition to not always being necessary, `network-online.target` isn't sufficient.  Just because the system has brought up some network interface, doesn't mean that it's brought up the interface we need for fetching the config.

We could indeed monitor the routing tables, but that's more work, and the current approach works fine.
