### ISSUE TITLE
Rework Filesystems for 3.0.0

### ISSUE THREAD

**Issue by ajeddeloh** [coreos/ignition#669]
# Background

Ignition should support a separate `/var` partition and support dividing `/var` up even further among more partitions. On ostree systems, `/var` is empty by default and should be populated by `systemd-tmpfiles` after the disks stage. For this to work, all of the partitions under `/var` must be mounted in the appropriate places. Currently there is no way to do this.

# Proposal

Change the `filesystems` and `files` (and `directories` and `links` but I'll just use `files` for brevity in this doc) entries as follows:

* flatten `storage.filesystems` as described in https://github.com/coreos/ignition/issues/650
* replace the `storage.filesystems[i].name` key with a `storage.filesystems[i].subpath` key (name subject to change).  This is where the filesystem will be mounted relative to `/sysroot` in the initramfs for `systemd-tmpfiles` and the files stage. If the path does not exist, leading directories will be created.
* remove the `storage.filesystems[i].path` key since it is now covered by subpath.
* remove the `storage.files[i].filesystem` key since the path alone is all that is needed.

This change would add another two stages to Ignition: `mount` and `umount`. In the mount stage all of the filesystems would be mounted (from shallowest to deepest) on `/sysroot` in the initramfs. They will be mounted at the path defined by `subpath` (relative to `/sysroot`). This would allow systemd-tmpfiles to have a correct directory structure to operate on. The `umount` stage just unmounts everything that `mount` mounted. Ignition Files would also operate on this directory structure, eliminating the need to specify which filesystem a file belongs to. 

The new initramfs ordering would be:
1) Ignition Disks
1) root partition is mounted at `/sysroot` by the initramfs
1) Ignition Mount
1) systemd-tmpfles
1) Ignition Files
1) Ignition Umount
1) Switch root

### Benefits:
 * Users specify paths for files/dirs/links as they would on a running system
 * `systemd-tmpfiles` can populate `/var` correctly

### Constraints to ensure correctness:
* `storage.filesystems[i].subpath` must be an absolute path with no symlinks to allow validation code to reason about conflicts.
* All paths for files and links must not be part of any subpath. Directories are ok.

### Misc. Gotchas:
* `storage.filesystems[i].subpath` is _not_ necessarily where the partition will be mounted in the real root (although in practice this will be the case for most configs). It does _not_ write out `/etc/fstab` entries or mount units. It is purely where the filesystem should be mounted in the initramfs for Ignition's use.
* Since writing files/links/directories does follow symlinks, users can still specify files/links that are part of a subpath. This cannot be checked at validation time, but can be checked on the running system, which is not ideal, but better than booting with ambiguous behavior.

### The default partition layout:
Ignition would need knowledge of the default partition layout to ensure `/var` is mounted even when Ignition itself is not creating the partition. This could be done by moving the [universal base config](https://github.com/coreos/ignition/blob/master/doc/getting-started.md#providing-a-config) out of the codebase and into the `/boot` partition. This would make it more flexible for other distros that wish to have different partition layouts.

With spec 3.0.0 the appending logic will be fixed such that duplicate filesystem entries (keyed on the subpath) would be replaced. This means the user can override the default `/var`entry with their own. Note: we need to ensure the device containing `/var` can be addressed by `/dev/disk/by-*`.

### Open questions:
* Ignition would create leading directories to the filesystem mount points. Is this an intended side effect?
   * If yes, we should allow users to specify the created directories should not exist (maybe something like `storage.nonexistents[i]`?)
   * If no, we need to ensure Ignition both keeps track of the leading directories it creates and ensures that they would not also be created by `systemd-tmpfiles`. This could be achieved by first running systemd-tmpfiles on a dummy `var` then copying it's contents.

Example:

```json
{
  "ignition": {
    "version": "3.0.0"
  },
  "storage": {
    "filesystems": [
      {
        "device": "/dev/sdb1",
        "subpath": "/var",
        "format": "xfs"
      },
      {
        "device": "/dev/sdb2",
        "subpath": "/var/log",
        "format": "ext4"
      }
    ],
    "files": [
      {
        "path": "/var/foo",
        "contents": {
          "source": "https://example.com/afile"
        }
      },
      {
        "path": "/var/log/bar",
        "contents": {
          "source": "https://example.com/anotherfile"
        }
      }
    ]
  }
}
```

cc @jlebon in case I missed anything and @bgilbert to ensure I got the "run systemd-tmpfiles on a dummy directory" idea right.

**Comment by bgilbert** [comment]
If the universal base config doesn't need to be user-configurable or vary across platforms, it'd be cleaner to put it in `/usr/share/ignition` inside the initramfs.

Is there a reason to use `subpath` rather than `path` or `mountpoint`?

I think creation of leading directories is harmless for mountpoints that will be used in the booted system, since systemd would create them anyway.  The issue is temporary mountpoints used only during the Ignition run, perhaps for filesystems that won't be mounted in the booted system.  Thoughts on that case:
- `storage.nonexistents` seems like a clunky way to handle it, especially since it would need to be processed during the umount phase.
- On further reflection I'm not sure I like the systemd-tmpfiles hack either, since it defeats some of the generality of this scheme.
- Maybe we could recommend that temporary mountpoints be placed underneath `/tmp`, and then delete such mountpoints during umount as a special case?  (The special case might just be the mount stage mounting a tmpfs on `/tmp`.  It doesn't make sense for configs to place actual files there, since they'd have a tmpfs mounted over them in the booted system.)

**Comment by ajeddeloh** [comment]
> If the universal base config doesn't need to be user-configurable or vary across platforms, it'd be cleaner to put it in /usr/share/ignition inside the initramfs.

Sure

> Is there a reason to use subpath rather than path or mountpoint?

Nope. Bikeshed away! I think there was some concern that `mountpoint` might be confusing since we're not also writing out mount units

> storage.nonexistents seems like a clunky way to handle it, especially since it would need to be processed during the umount phase.

Hmm, hadn't thought of the fact it would need to happen as we umount things. Gross. 

> Maybe we could recommend that temporary mountpoints be placed underneath /tmp, and then delete such mountpoints during umount as a special case? (The special case might just be the mount stage mounting a tmpfs on /tmp. It doesn't make sense for configs to place actual files there, since they'd have a tmpfs mounted over them in the booted system.)

Hrm. That also feels a little hacky. I'd almost rather have a flag for "delete my leading directories" or something. Special handling based on path isn't great and is pretty unintuitive. One idea we floated was keeping the `name` field on filesystems and using the old behavior if you used that instead of `subpath`, but that's also confusing.

**Comment by bgilbert** [comment]
> I think there was some concern that mountpoint might be confusing since we're not also writing out mount units

Sure.

> Special handling based on path isn't great and is pretty unintuitive.

It gave me pause as well.  OTOH, things in `/tmp` are normally not expected to persist, so in the sense of Unix semantics it's arguably quite intuitive.  :slightly_smiling_face:

**Comment by jlebon** [comment]
Proposal looks sane to me and corresponds to what we discussed!

> Is there a reason to use `subpath` rather than `path` or `mountpoint`?

The reason for `subpath` is mostly that it reinforces the fact that the filesystem will be mounted underneath `/sysroot`, which wasn't the case previously. Not too attached to it though. The name `path` itself is OK, but it already has a connotation from the current spec.

> I'd almost rather have a flag for "delete my leading directories" or something.

That sounded nice at first, but I think this could still cause issues re. systemd-tmpfiles. E.g. one may enable that option to delete leading dirs, but then a newer image includes a tmpfiles entry for one of those paths and now we'd be deleting dirs that normally would exist if there was a better "throwaway" functionality. 

> > Special handling based on path isn't great and is pretty unintuitive.
>
> It gave me pause as well. OTOH, things in `/tmp` are normally not expected to persist, so in the sense of Unix semantics it's arguably quite intuitive. :slightly_smiling_face: 

Yeah, I think that could work and the semantics are indeed well understood. (Although... not all systems *necessarily* have tmpfs-on-tmp, right? E.g. Fedora Atomic Host today doesn't do this, though it's easy to enable via cloud-init. But I'd agree one shouldn't be relying on that either way :slightly_smiling_face: since e.g. IIRC there's a systemd tmpfile entry to nuke `/tmp` every $x days).

**Comment by ajeddeloh** [comment]
> On further reflection I'm not sure I like the systemd-tmpfiles hack either, since it defeats some of the generality of this scheme.

Can you expand on that?

**Comment by bgilbert** [comment]
> Can you expand on that?

Using a parallel tmpfiles tree is not orthogonal to the mount/umount stages.  The point of the latter is to allow the distro to do arbitrary additional things to the filesystem tree specified in the config.  If those additional things can be efficiently represented as a separate hierarchy, the mount/umount stages are unnecessary: if the files stage will be responsible for copying a prepopulated tree anyway, it might as well just do that.  But the prepopulated tree has limitations:

- It probably shouldn't include large files that would incur too much copying overhead.
- The distro might have some reason to manipulate the mounted hierarchy directly (mounting additional filesystems not specified by the config, generating an fstab, whatever).

**Comment by bgilbert** [comment]
@ajeddeloh convinced me OOB that since Ignition doesn't otherwise have any semantics for paths within `/sysroot`, special-casing `/tmp` in Ignition doesn't feel right.

An alternative is to have the distro, not Ignition, provide the special `/tmp` semantics.  Specifically:
- Ignition's mount semantics could specify that it unconditionally leaves mount points behind.
- Before the `mount` stage, the distro could mount a tmpfs on `/sysroot/tmp`.  After `umount`, it could unmount `/sysroot/tmp`.
- The _distro_ could recommend that temporary subpath bindings be placed in `/tmp`.

This would still allow the future addition of a config option to delete specific mountpoints on the way out, though the distro would need to keep mounting a tmpfs on `/sysroot/tmp` for compatibility.

**Comment by ajeddeloh** [comment]
I'm in favor of that. We'll just want to document "this is how you format something you don't want to create mountpoints for" and make that clear to migrating users.

**Comment by ajeddeloh** [comment]
Mostly implemented by https://github.com/coreos/ignition/pull/718.

Closing this and opening https://github.com/coreos/ignition/issues/740 to wrap up the work
