### ISSUE TITLE
load systemd units content from remote source

### ISSUE THREAD

**Issue by sergey-safarov** [coreos/ignition#673]
# Feature Request #

## Environment ##
```
ip-192-168-4-138 ~ # cat /etc/os-release 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1911.4.0
VERSION_ID=1911.4.0
BUILD_ID=2018-11-26-1924
PRETTY_NAME="Container Linux by CoreOS 1911.4.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

## Desired Feature ##
I want manage units as dedicated files on GitHub repo. This units need use from yaml file instead of embedding into.
Could you add ability do define source of systemd units.

## Other Information ##
none

**Comment by ajeddeloh** [comment]
I have mixed feelings about this. I like the idea in principle but the details make it a little harder. This would require a major version bump for Ignition since they contents field would change for the unit. We're currently working on the 3.0.0 spec, but that won't ever ship with Container Linux (it will instead ship with the first release of FCOS). Additionally, sources are not validated by the validation code. This would mean changing a validation error into a boot-time error if the unit is invalid.

I think this might be a better fit for [`ct`](https://github.com/coreos/container-linux-config-transpiler/blob/master/doc/configuration.md). If we changed `ct` (which has much less strict versioning) to support this instead, it could resolve the units when transpiling and validate their contents without changing the Ignition spec.

**Comment by sergey-safarov** [comment]
Looks as `ct` will be enough for this.
Where i can create feature request for `ct`?

**Comment by ajeddeloh** [comment]
[CoreOS Bugs](https://github.com/coreos/bugs/issues) is probably the best place.

**Comment by sergey-safarov** [comment]
Created
This ticket is closed
