### ISSUE TITLE
Create filesystems in parallel

### ISSUE THREAD

**Issue by aughr** [coreos/ignition#681]
# Feature Request #

## Environment ##

Bare metal hosts with many JBOD SSDs.

## Desired Feature ##

It would be very nice to be able to create filesystems on each SSD in parallel. As far as I can tell, Ignition currently executes that serially, which is far slower than it might otherwise be.

## Other Information ##

I don't know if there's a good reason not to do this work in parallel.

**Comment by ajeddeloh** [comment]
Ignition does in fact do them serially. I agree, there's no reason not to do them in parallel. Probably want to limit it to N at a time where N is the number of cores or GOMAXPROCS or similar. Related but distinct is https://github.com/coreos/ignition/issues/581. These do not interfere since filesystems always happen after _all_ partitioning/raid creation.

**Comment by aughr** [comment]
Thanks @ajeddeloh. Would you be interested in a PR to support this? If so, any advice on how to test that kind of functionality?

**Comment by ajeddeloh** [comment]
Absolutely. I'm not sure it's worth testing "did this run in parallel", but we still want to ensure the result is the same. You could probably just a test in `tests/positive/filesystems` that creates a bunch of partitions/filesystems. Should be pretty similar to the existing filesystem tests. See `doc/development.md` for details on how to run the tests locally.

**Comment by bgilbert** [comment]
Thanks for pointing this out!

Parallel creation of multiple filesystems on the same rotating disk might be slower than serial creation.  We could detect and avoid that case, but it's an increasingly obscure one and doesn't seem worth the effort.
