### ISSUE TITLE
Release ignition as binary

### ISSUE THREAD

**Issue by n0rad** [coreos/ignition#736]
I would like to test & use ignition out of Container Linux on a PXE boot sequence.
I'm not sticked to a distro so I don't want to create packages.
I don't really want to maintain a build process on my side as a copy of your travis build or Contraine Linux ebuild.

Can you provide Ignition binaries as github releases like you are already doing for the validator ?

**Comment by bgilbert** [comment]
I don't think we should do this.  The Ignition binary will not be useful for most users, and the process of integrating it into a distro is somewhat intricate.  Uploading binaries is likely to cause confusion without providing much value.

You should be able to build Ignition by checking out the repo and running `./build`.

**Comment by ajeddeloh** [comment]
Ignition binaries are somewhat of a footgun. They are incredibly dangerous to run on your host since Ignition will happily blow away files/directories, and given enough permissions, your entire disk. They're also distro specific since they hardcode paths to utilities (we're look to change that eventually) and gentoo's paths are often not the same as other distros.

Building Ignition doesn't require much, you need go and `libblkid` (might be part of `util-linux`, depending on how your distro packages things).

I'm closing this as WONTFIX, if you have trouble building, feel free to open a new issue.
