### ISSUE TITLE
Unclear how to install?

### ISSUE THREAD

**Issue by purpleidea** [coreos/ignition#763]
This looks interesting and I'd like to give it a try.

I'm interested in using this with either a recent Fedora, CentOS or Debian machine.

How do I get the necessary stuff into (AIUI) the initramfs so that it actually runs on first boot? I'll be running on a physical host.

As a second question, how do I do the same when I'm running one of those in a libvirt vm?

Thanks!

**Comment by dustymabe** [comment]
There are a few components to this. For fedora coreoos we are using the dracut modules in https://github.com/coreos/ignition-dracut repo (and trying to make that repo distro agnostic). How this comes together can be seen in the igition rpm in fedora: https://src.fedoraproject.org/rpms/ignition 

That should get you started and generate a few more questions :)

**Comment by purpleidea** [comment]
> https://github.com/coreos/ignition-dracut repo

Aha! I figured dracut, but I could not find dracut in this repo. I would recommend either merging the two or prominently mentioning this in the docs and README somewhere.

Fantastic!

So let's say I'm using bare metal from https://coreos.com/ignition/docs/latest/supported-platforms.html
and I want to use the `coreos.config.url` kernel param to point to `https://whatever/...` how do I glue this together? Do I have to get kickstart to install the ignition rpm, and somehow set the kernel url, or is there a better way to bypass kickstart entirely??

Thanks!

**Comment by dustymabe** [comment]
> Do I have to get kickstart to install the ignition rpm, and somehow set the kernel url, or is there a better way to bypass kickstart entirely??

for a traditional install i would install the ignition rpm using kickstart. The next part is a bit tricky but basically you need to set `ignition.firstboot` on the kernel command line to trigger an ignition run. However, you only want ignition to run on first boot so you want to dynamically add it to the kernel command line based on whether it is the first boot or not. We use a file in `/boot/ignition.firstboot` to denote this for FCOS and we have a systemd unit that deletes that file so that it's not there for subsequent boots.

Once you've got all this wired up you can set `coreos.ignition.url` (we recently changed it to make it not specific to coreos) and have that ignition config get picked up and applied.  

There is slightly more information at https://github.com/coreos/ignition-dracut/issues/39#issuecomment-454028257

and then set `$ignition_firstboot` on the kernel command line

**Comment by bgilbert** [comment]
For context: Ignition has historically only been used on CoreOS Container Linux.  We're working on integrating it into the upcoming Fedora CoreOS and Red Hat CoreOS distros, and that work should benefit the rest of Fedora as well.  But at the moment I'd expect running Ignition on an arbitrary distro to require some effort.  Please let us know how things work for you!

https://github.com/coreos/ignition/issues/649 may be of some help as well.

**Comment by purpleidea** [comment]
Gotcha! Well I don't have a full environment setup to test all this at the moment, so I must thank you for your time, and come back to this later!

Basically to solve the `bootstrapping iron` problem, I'm looking at having say https://github.com/purpleidea/mgmt/ setup tftp/dhcp/kickstart and then perhaps have something like this kick it all off.

Once I get that base infra running, I can come back when I don't know why it's not working :/

Am I correct in understanding that in theory, if I ran some kickstart commands (including adding ignition) that after ignition runs, it could basically undo some of the kickstart provisioning that it just did?

**Comment by purpleidea** [comment]
@bgilbert Understood! Looking forward to it being more seamless in the distros, but I'm patient. Thanks!

**Comment by ajeddeloh** [comment]
> Am I correct in understanding that in theory, if I ran some kickstart commands (including adding ignition) that after ignition runs, it could basically undo some of the kickstart provisioning that it just did?

Yes.

I'm closing this as a dup of #649. If you feel it's substantially different, feel free to reopen.
