### ISSUE TITLE
Ignition cannot create hard links to files it creates deeper than the link

### ISSUE THREAD

**Issue by ajeddeloh** [coreos/ignition#800]
# Bug #

## Ignition Version ##
v2.0.0+

## Expected Behavior ##

Ignition can create hard links to files  (or symlinks) that are also specified in a config that are as deep or deeper than the hard link.

## Actual Behavior ##
Ignition will fail since the hard link is created before the target

## Reproduction Steps ##
```
{
  "ignition": { "version": "3.0.0" },
  "storage": {
    "files": [{
      "path": "/foo/bar/baz"
    }],
    "links": [{
      "path": "/foo/quux",
      "target": "/foo/bar/baz",
      "hard": true
    }]
  }
}
```

**Comment by jlebon** [comment]
So to go in more details on what I think the bug is here: Ignition by default creates paths from shallowest to deepest. This allows for example the creation of directories with custom modes/permissions to happen before any files specified under them.

In this case, it wants to create `/foo/quux` first. But that will fail because it's a hard link to `/foo/bar/baz` which hasn't been created yet.

One simple fix for this is to just delay hard link creation until the end. I don't think we want to delay *all* links, because e.g. a directory symlink should still be created before any files that go under it.

**Comment by lucab** [comment]
> One simple fix for this is to just delay hard link creation until the end. I don't think we want to delay all links, because e.g. a directory symlink should still be created before any files that go under it.

Self note: drawing a line here between hard and symbolic links makes sense when looking at the FS level too, because directory hard-links are not allowed (while directory sym-links are).
