### ISSUE TITLE
Support CA bundles for Ignition config

### ISSUE THREAD

**Issue by miabbott** [coreos/ignition#931]
We have seen reports of RHCOS/OCP users trying to provide CA bundles that include a Root CA and an Intermediate CA for the purposes of fetching the Ignition configs (i.e. `security.tls.certificateAuthorities.`)

It would be useful if Ignition supported these bundles rather than requiring users to split the CAs in to separate entries in the config file.

See downstream BZs:

https://bugzilla.redhat.com/show_bug.cgi?id=1808286
https://bugzilla.redhat.com/show_bug.cgi?id=1809780

**Comment by miabbott** [comment]
Since this is affecting RHCOS, we would like to see this functionality in spec v2 and v3.

**Comment by lucab** [comment]
I have a feeling that the underlying issue here is that, while the Ignition doc is explicit about importing single certificate per item, the code doesn't actually check that and just ignore any subsequent data.

Looking at the two BZs, I'd rather suggest to start actually failing if there are multiple certificates provided in a single item.

From an high-level point of view, the goal is to anchor one client trust chain to one trusted entity, which could be either (depending on customer choices):
 * the parent one, giving the signer flexibility to switch intermediate (which has to be provided by the server in its chain)
 * the child one, denying further intermediate switching (and not requiring the whole chain)

Having to provide two entities to trust for a single trust chain is an indicator that something in the infrastructure is not setup properly. I'd argue that it is useful to keep that signal, instead of papering over it.

**Comment by cgwalters** [comment]
> Having to provide two entities to trust for a single trust chain is an indicator that something in the infrastructure is not setup properly.

I see a use case for this around certificate rotation - it's much easier for admins to do this by introducing a new cert, gradually rolling out the change, ensuring their systems trust it.  Then remove the old cert from the trust bundle.

**Comment by cgwalters** [comment]
I agree though what the people from the BZs are doing in providing a parent *and* an intermediate is probably wrong, but I also understand why they do it.

Another angle on this is that the host OS supports multiple certificates in `/etc/pki/ca-trust/source/anchors`.  And probably Ignition should support dropping those into the initramfs, so that anything *else* that wants to use certs in the initramfs (e.g. [NBDE with Tang](https://github.com/latchset/clevis/)) could also use them.

**Comment by jlebon** [comment]
Hmm, just looking at the two RHBZs linked, they're trying to do different things. One is about wanting to trust all the certs in a chain (which I agree with @lucab in https://github.com/coreos/ignition/issues/931#issuecomment-595239333 feels wrong), the other I think seems to be about simply having multiple independent root certificates in the same bundle, which I think makes sense, no? Not just for root cert rotation, but just in general, that's how one specifies multiple certificates, right? (And e.g. why we have `update-ca-trust` to regenerate the CA bundles.)

So IOW unless I'm misunderstanding (definitely not a PKI expert!), while it may be misused, it seems reasonable to me for users to assume that we match how other software behave when provided a CA bundle and trust all the certs in the list, not just the first one.

**Comment by lucab** [comment]
Don't get me wrong, I agree there are many usecases for having multiple trust anchors (but pointing out that "chain of intermediates" does not belong to that bucket).
But I believe that this was accounted for in the initial design by having `certificateAuthorities` as a **list** of entries (i.e. single certificates), allowing for multiple anchors (even coming from different Ignition merged fragments).

That said, `update-ca-trust` clearly disagrees with me as it happily takes a `/etc/pki/ca-trust/source/anchors/my-cert-foo.crt` with multiple certificates inside, propagating all of them to `/etc/pki/tls/certs/ca-bundle.trust.crt`. As opposed to Ignition asking for `my-cert-foo.crt` and `my-cert-bar.crt` in order to propagate them to the (internally) trusted bundle.

**Comment by lucab** [comment]
Additional datapoint: Ignition models an API for its trust store which is in principal similar to [OpenSSL CApath](https://www.openssl.org/docs/man1.0.2/man1/openssl-verify.html), that is a list of trust anchors. I just checked OpenSSL behavior, and `c_rehash` accepts the case where a file contains more than one certificate (it trusts/hashes them separately, pointing to the same file).

Even if I'm not super happy with an API that accepts both "list of certificate entries" and "list of multi-certificates entries", I think @jlebon point of consistent behavior with other PKI tools overrules this.
